//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace EntityFrameworkTest
{
    public partial class TestPerformaceDBEntities : ObjectContext
    {
        public const string ConnectionString = "name=TestPerformaceDBEntities";
        public const string ContainerName = "TestPerformaceDBEntities";
    
        #region Constructors
    
        public TestPerformaceDBEntities()
            : base(ConnectionString, ContainerName)
        {
        }
    
        public TestPerformaceDBEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
        }
    
        public TestPerformaceDBEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Categories> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Categories>("Categories")); }
        }
        private ObjectSet<Categories> _categories;
    
        public ObjectSet<Customers> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customers>("Customers")); }
        }
        private ObjectSet<Customers> _customers;
    
        public ObjectSet<Products> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Products>("Products")); }
        }
        private ObjectSet<Products> _products;

        #endregion
    }
}
